enum InputDSType {
  SEARCH = 'SEARCH',
  SELECT = 'SELECT',
  CODE = 'CODE',
  TEXT_AREA = 'TEXT_AREA',
  TEXT = 'TEXT',
  PASSWORD = 'PASSWORD',
  PHONE_NUMBER = 'PHONE_NUMBER',
  MONEY = 'MONEY',
  EXPIRATION_DATE = 'EXPIRATION_DATE',
  ALPHABETIC = 'ALPHABETIC',
  ALPHANUMERIC = 'ALPHANUMERIC',
  NUMERIC = 'NUMERIC',
  MAIL = 'MAIL',
}

export default InputDSType;
